### ISSUE TITLE
keymap 毎の glcdfont.c について

### ISSUE THREAD

**Issue by mtei** [mtei/qmk_firmware#1]
https://twitter.com/pluis9/status/978866831397195776 を検討して見ました。

qmk_firmware/keyboards/helix/ssd1306.c の中で
`#include "common/glcdfont.c"`
を行っています。

gcc 起動時のオプションで、include関係は以下のようになっています。
```
-I keyboards/helix/rev2/keymaps/キーマップ名 \
-I keyboards/helix \
-I keyboards/helix/rev2 \
.... \
-include keyboards/helix/config.h \
-include keyboards/helix/rev2/config.h \
-include keyboards/helix/rev2/keymaps/five_rows/config.h \

```

ssd1306.c の中で 
`#include <common/glcdfont.c>` を行っていた場合、インクルード検索パス指定の順に従って
`keyboards/helix/rev2/keymaps/キーマップ名/common/glcdfont.c` を最初に探します。

しかし、`#include "common/glcdfont.c"` の場合、インクルード検索パス指定を試す以前に
まずインクルード元のソースのあるディレクトリを試します。
なので、常に、`qmk_firmware/keyboards/helix/common/glcdfont.c` を最初に
調べてしまい、切り替え不可能です。

したがって、一番簡単には、

1. ssd1306.c を `#include <common/glcdfont.c>` に変更。
2. カスタマイズしたいキーマップでは、`qmk_firmware/keyboards/helix/rev2/keymaps/キーマップ名/common/glcdfont.c` を置く。

となります。（実験済み)

しかし、`keymaps/キーマップ名/common/`　を作るのはなんだかちょっと気持ち悪いです。
なので、もう一つの案

1. `helix/common/glcdfont.c` を移動し改名 `helix/glcdfont.h`
2. ssd1306.c を `#include <glcdfont.h>` に変更。
3. カスタマイズしたいキーマップでは、`qmk_firmware/keyboards/helix/rev2/keymaps/キーマップ名/glcdfont.h` を置く。

となります。

上のどちらかを行えば、keymap 毎の glcdfont.c は達成できそうです。

**Comment by mtei** [comment]
上の検討をもとに、今現在の qmk/ の master を起点にしたブランチ helix-change-glcdfont_c で実験してみました。

* helix/ssd1306.c を変更。(最初の commit)
  LOCAL_GLCDFONTマクロの定義があったら、common/glcdfont.c の代わりに helixfont.h を include するように変更しました。
  誤って qmk_firmware/drivers/avr/glcdfont.c を include しないように、helixfont.h としました。　keymap/xxx/rules.mk に変更が無い限り、いままでと同じコンパイル結果になるように留意しました。

* default/rules.mk, five_rows/rules.mk を変更。(二番目の commit)
  カスタマイズ項目として、LOCAL_GLCDFONT = no/yes を追加して、helix/ssd1306.c の include するファイルの切り替えを指定できるようにしました。
  keymap/{default|five_rows}/rules.mk を LOCAL_GLCDFONT = yes にして、keymap/{default|five_rows}/helixfont.h を用意（common/glcdfont.cをコピーして名前を変える）すれば、そちらが使われるようになっています。。

**Comment by MakotoKurauchi** [comment]
ありがとうございます。
やはりファイル名は変えた方が無難ですかね。
これで行きましょう。
PRお願いします！
