### ISSUE TITLE
Make quantum/split_common/serial.h configurable.

### ISSUE THREAD

**Issue by mtei** [mtei/qmk_firmware#3]
# THIS IS DRAFT for English checking

(私は英語は苦手なので、日本語で書いて、google で翻訳します。)
( I am not good at English, so write in Japanese and translate it with google.)
 
私は、`quantum/split_common/serial.h` から ポートの定義を分離する事を提案します。
I propose separating the port definitions from `quantum/split_common/serial.h` .
 
多くのキーボードは、PD0 を使っていますが、いくつかのキーボードは PD2 を使っています。
Many keyboards use `PD0`, but some keyboards use `PD2`.
 
従って、ポートの定義は、`quantum/split_common/serial.h` から削除して、新しく用意する `serial_config.h` に記述する方が良いと思う。
Therefore, I think that it is better to delete the port definitions from `quantum/split_common/serial.h` and write it in `serial_config.h` which is newly prepared.
 ( `keyboards/A_KEYBOARD/config.h` needs `#include <serial_config.h>` )
 
PD0 を使う場合の `serial_confg.h` のサンプル
Sample `serial_confg.h` when using `PD0`.
```c
#ifndef SOFT_SERIAL_CONFIG_H
#define SOFT_SERIAL_CONFIG_H

/* Soft Serial defines */
#define SERIAL_PIN_DDR DDRD
#define SERIAL_PIN_PORT PORTD
#define SERIAL_PIN_INPUT PIND
#define SERIAL_PIN_MASK _BV(PD0)
#define SERIAL_PIN_INTERRUPT INT0_vect

#define SERIAL_SLAVE_BUFFER_LENGTH MATRIX_ROWS/2
#define SERIAL_MASTER_BUFFER_LENGTH 1

#endif /* SOFT_SERIAL_CONFIG_H */
```

PD2 を使う場合の `serial_confg.h` のサンプル
Sample `serial_confg.h` when using `PD2`.
```c
#ifndef SOFT_SERIAL_CONFIG_H
#define SOFT_SERIAL_CONFIG_H

/* Soft Serial defines */
#define SERIAL_PIN_DDR DDRD
#define SERIAL_PIN_PORT PORTD
#define SERIAL_PIN_INPUT PIND
#define SERIAL_PIN_MASK _BV(PD2)
#define SERIAL_PIN_INTERRUPT INT2_vect

#define SERIAL_SLAVE_BUFFER_LENGTH MATRIX_ROWS/2
#define SERIAL_MASTER_BUFFER_LENGTH 1

#endif /* SOFT_SERIAL_CONFIG_H */
```

`quantum/split_common/serial.c` の `void serial_slave_init(void)` を以下のように変更する。
Change `void serial_slave_init (void)` of `quantum/split_common/serial.c` as follows.
```c
void serial_slave_init(void) {
    serial_input_with_pullup();

#if SERIAL_PIN_MASK == _BV(PD0)
    // Enable INT0
    EIMSK |= _BV(INT0);
    // Trigger on falling edge of INT0
    EICRA &= ~(_BV(ISC00) | _BV(ISC01));
#elif SERIAL_PIN_MASK == _BV(PD2)
    // Enable INT2
    EIMSK |= _BV(INT2);
    // Trigger on falling edge of INT2
    EICRA &= ~(_BV(ISC20) | _BV(ISC21));
#else
 #error unknown SERIAL_PIN_MASK value
#endif
}
```

**Comment by nmyeti** [comment]
> 私は、quantum/split_common/serial.h から ポートの定義を分離する事を提案します。

I would suggest separating port definitions from quantum/split_common/serial.h .

> 従って、ポートの定義は、quantum/split_common/serial.h から削除して、新しく用意する serial_config.h に記述する方が良いと思う。

Therefore, I think it's better to delete the port definitions from quantum/split_common/serial.h and write it in newly prepared serial_config.h.


> PD0 を使う場合の serial_confg.h のサンプル

Here is a sample serial_confg.h with using PD0.

> PD2 を使う場合の serial_confg.h のサンプル

Here is a sample serial_confg.h with using PD2.

**Comment by nmyeti** [comment]
> (私は英語は苦手なので、日本語で書いて、google で翻訳します。)
( I am not good at English, so write in Japanese and translate it with google.) 

の文は無しで，元の日本語も付けなくてOKだと思います

**Comment by mtei** [comment]
# THIS IS DRAFT Take 2 for English checking

I would suggest separating port definitions from `quantum/split_common/serial.h` .
 
Many keyboards use `PD0`, but some keyboards use `PD2`  as follows.

```
% find quantum keyboards -name 'ser*.h' | xargs grep  SERIAL_PIN_MASK  | grep PD2
keyboards/crkbd/serial.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/ergoinu/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/fortitude60/serial.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/helix/pico/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/helix/rev2/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/mint60/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
```

Therefore, I think it's better to delete the port definitions from `quantum/split_common/serial.h` and write it in newly prepared `quantum/split_common/serial_config.h`.

 
Change `quantum/split_common/serial.h`  as follows.
```c
#ifndef SOFT_SERIAL_H
#define SOFT_SERIAL_H

#include <stdbool.h>

// Each keyboard can override serial_config.h
//
// serial_config.h search sequence:
//   keyboards/KEYBOARD_NAME/keymaps/MAP_NAME/serial_config.h
//   keyboards/KEYBOARD_NAME[/rev?]/serial_config.h
//   quantum/split_common/serial_config.h
#include <serial_config.h>

// Buffers for master - slave communication
extern volatile uint8_t serial_slave_buffer[SERIAL_SLAVE_BUFFER_LENGTH];
extern volatile uint8_t serial_master_buffer[SERIAL_MASTER_BUFFER_LENGTH];

void serial_master_init(void);
void serial_slave_init(void);
int serial_update_buffers(void);
bool serial_slave_data_corrupt(void);

#endif
```

Create `quantum/split_common/serial_config.h` as follows.
```c
#ifndef SOFT_SERIAL_CONFIG_H
#define SOFT_SERIAL_CONFIG_H

// Soft Serial defines
#define SERIAL_PIN_DDR DDRD
#define SERIAL_PIN_PORT PORTD
#define SERIAL_PIN_INPUT PIND
#define SERIAL_PIN_MASK _BV(PD0)
#define SERIAL_PIN_INTERRUPT INT0_vect

#define SERIAL_SLAVE_BUFFER_LENGTH MATRIX_ROWS/2
#define SERIAL_MASTER_BUFFER_LENGTH 1

// Address location defines
#define SERIAL_BACKLIT_START   0x00

#endif // SOFT_SERIAL_CONFIG_H
```

Change `void serial_slave_init (void)` of `quantum/split_common/serial.c` as follows.
```c
void serial_slave_init(void) {
    serial_input();

#if SERIAL_PIN_MASK == _BV(PD0)
  // Enable INT0
  EIMSK |= _BV(INT0);
  // Trigger on falling edge of INT0
  EICRA &= ~(_BV(ISC00) | _BV(ISC01));
#elif SERIAL_PIN_MASK == _BV(PD2)
  // Enable INT2
  EIMSK |= _BV(INT2);
  // Trigger on falling edge of INT2
  EICRA &= ~(_BV(ISC20) | _BV(ISC21));
#else
 #error unknown SERIAL_PIN_MASK value
#endif
}
```

**Comment by Woovie** [comment]
I recommend the following changes:
From
```Therefore, I think it's better to delete the port definitions from `quantum/split_common/serial.h` and write it in newly prepared `quantum/split_common/serial_config.h`.```
To
```Therefore, I think it's better to move the port definitions from `quantum/split_common/serial.h` to a new file, `quantum/split_common/serial_config.h`.```

From
```Change `void serial_slave_init (void)` of `quantum/split_common/serial.c` as follows.```
To
```Within `quantum/split_common/serial.c` change `void serial_slave_init (void)` as follows.```

**Comment by mtei** [comment]
Thenk you for your comment.

I will fix them.
And I add a line.
"May I PullRequest with the following changes?"

**Comment by mtei** [comment]
# THIS IS last DRAFT for English checking

I would suggest separating port definitions from `quantum/split_common/serial.h` .
 
Many keyboards use `PD0`, but some keyboards use `PD2`  as follows.

```
% find quantum keyboards -name 'ser*.h' | xargs grep  SERIAL_PIN_MASK  | grep PD2
keyboards/crkbd/serial.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/ergoinu/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/fortitude60/serial.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/helix/pico/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/helix/rev2/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
keyboards/mint60/serial_config.h:#define SERIAL_PIN_MASK _BV(PD2)
```

Therefore, I think it's better to move the port definitions from `quantum/split_common/serial.h` to a new file, `quantum/split_common/serial_config.h`

May I PullRequest with the following changes?
 
Change `quantum/split_common/serial.h`  as follows.
```c
#ifndef SOFT_SERIAL_H
#define SOFT_SERIAL_H

#include <stdbool.h>

// Each keyboard can override serial_config.h
//
// serial_config.h search sequence:
//   keyboards/KEYBOARD_NAME/keymaps/MAP_NAME/serial_config.h
//   keyboards/KEYBOARD_NAME[/rev?]/serial_config.h
//   quantum/split_common/serial_config.h
#include <serial_config.h>

// Buffers for master - slave communication
extern volatile uint8_t serial_slave_buffer[SERIAL_SLAVE_BUFFER_LENGTH];
extern volatile uint8_t serial_master_buffer[SERIAL_MASTER_BUFFER_LENGTH];

void serial_master_init(void);
void serial_slave_init(void);
int serial_update_buffers(void);
bool serial_slave_data_corrupt(void);

#endif
```

Create `quantum/split_common/serial_config.h` as follows.
```c
#ifndef SOFT_SERIAL_CONFIG_H
#define SOFT_SERIAL_CONFIG_H

// Soft Serial defines
#define SERIAL_PIN_DDR DDRD
#define SERIAL_PIN_PORT PORTD
#define SERIAL_PIN_INPUT PIND
#define SERIAL_PIN_MASK _BV(PD0)
#define SERIAL_PIN_INTERRUPT INT0_vect

#define SERIAL_SLAVE_BUFFER_LENGTH MATRIX_ROWS/2
#define SERIAL_MASTER_BUFFER_LENGTH 1

// Address location defines
#define SERIAL_BACKLIT_START   0x00

#endif // SOFT_SERIAL_CONFIG_H
```

Within `quantum/split_common/serial.c` change `void serial_slave_init (void)` as follows.
```c
void serial_slave_init(void) {
    serial_input();

#if SERIAL_PIN_MASK == _BV(PD0)
  // Enable INT0
  EIMSK |= _BV(INT0);
  // Trigger on falling edge of INT0
  EICRA &= ~(_BV(ISC00) | _BV(ISC01));
#elif SERIAL_PIN_MASK == _BV(PD2)
  // Enable INT2
  EIMSK |= _BV(INT2);
  // Trigger on falling edge of INT2
  EICRA &= ~(_BV(ISC20) | _BV(ISC21));
#else
 #error unknown SERIAL_PIN_MASK value
#endif
}
```

**Comment by Woovie** [comment]
Perhaps a slight change?

From
```May I PullRequest with the following changes?```
To
```I think these changes would be beneficial to QMK. I would be glad to submit a pull request with these changes. Let me know your thoughts and opinions.```

**Comment by mtei** [comment]
Thank you Woovie.

I submitted to QMK done.
and close this entry.
